name = "ArmA-3-Mod-Template"
author = "Lupus590"
prefix = "template"
mainprefix = "z"

[version]
path = "addons/core/script_version.hpp"
git_hash = 0 # It's a shame that I can't get this to work

[files]
include = [
	"logo.paa",
	"changelog.md",
	"mod.cpp",
]

[hemtt.release]
folder = "ArmA-3-Mod-Template"

[hemtt.launch.default]
presets = [
	"main", # .html presets from .hemtt/presets/
]
parameters = [
	"-skipIntro",			# These parameters are passed to the Arma 3 executable
	"-noSplash",			# They do not need to be added to your list
	"-showScriptErrors",	# You can add additional parameters here
	"-debug",
	"-filePatching",
]
executable = "arma3_x64" # Default: "arma3_x64"
file_patching = false # Default: true
binarize = true # Default: false
rapify = false # Default: true
