name: "Changelog Reminder"
on:
- pull_request_target

jobs:
  changelog-reminder:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/changelog-reminder-action@v3.0.0
        with:
          changelogRegex: "changelog.md"
          message: "Please remember to update the changelog."
